config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'auth', :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :products
  resources :categories

  resources :users

  root to: 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  self.per_page = 5

  validates :name, presence: true

  has_and_belongs_to_many :products
end

app/models/product.rb
require 'carrierwave/orm/activerecord'

class Product < ActiveRecord::Base
  self.per_page = 5

  validates :name, presence: true
  validates :price, presence: true, numericality: true

  mount_uploader :image, ImageUploader

  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  self.per_page = 5

  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :super_admin can access any page regardless of access settings. Use with caution!  ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: true)                                      ##
  ############################################################################################


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  access user: {except: [:destroy]}, admin: :all

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.paginate(:page => params[:page])
  end

  def show
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully added'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  protected
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  access user: {except: [:destroy]}, admin: :all

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.includes(:categories)
                        .paginate(:page => params[:page])
  end

  def show
  end

  def edit
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully added'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully destroyed.'
  end

  protected
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :description,

      :image,
      :image_cache,

      category_ids: []
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  access admin: :all

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully added'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  protected
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_pagination_for(collection)
    will_paginate collection, renderer: BootstrapPagination::Rails
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.input :name, class: 'form-control' %>
  </div>

  <%= f.button :submit %>
<% end %>

app/views/categories/edit.html.erb
Edit category # <%= @category.id %>
<% if logged_in?(:admin) %>
  <%= button_to 'Delete ', @category, :method => :delete, class: 'btn btn-danger pull-right' %>
<% end %>

<%= render partial: 'form', category: @category %>

app/views/categories/index.html.erb
<a class="btn btn-primary" href="<%= new_category_path %>">Add New Category</a>

<table id="categories-list" class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-1">id</th>
      <th class="col-md-1">Name</th>
      <th class="col-md-2">Actions</th>
    </tr>
  </thead>
  <% for @category in @categories %>
    <tr>
      <td><%= @category.id %></td>
      <td><%= @category.name %></td>
      <td>
        <a class="btn btn-primary" href="<%= edit_category_path(@category) %>">Edit</a>
      </td>
    </tr>
  <% end %>
</table>
<%= bootstrap_pagination_for(@products) %>

app/views/categories/new.html.erb
Create new category

<%= render partial: 'form', category: @category %>

app/views/categories/show.html.erb
<h2>Category <%= @category.id %> info</h2>
<dl>
  <dt>ID</dt>
  <dd><%= @category.id %></dd>
  <dt>Name</dt>
  <dd><%= @category.name %></dd>
  <dt>Creation time</dt>
  <dd><%= @category.created_at %></dd>
  <dt>Updation time</dt>
  <dd><%= @category.updated_at %></dd>
</dl>

<a href="<%= edit_category_path(@category) %>" class="btn btn-primary">Edit</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Warehouse</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Warehouse", '/', class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="<%= products_path %>">Products</a>
          </li>
          <li class="active">
            <a href="<%= categories_path %>">Categories</a>
          </li>
          <% if logged_in?(:admin) %>
            <li class="active">
              <a href="<%= users_path %>">Users</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :image_cache, as: 'hidden' %>
  <div class="form-group">
    <%= f.input :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :description, class: 'form-control' %>
  </div>

  <dif class="form-group">
    <%= f.association :categories,
          collection: Category.all,
          input_html: { class: 'multiselectuser'}
    %>
  </dif>

  <div class="form-group">
    <%= image_tag(@product.image_url) if @product.image? %>
    <%= f.input :image, class: 'form-control' %>
  </div>

  <%= f.button :submit %>
<% end %>

app/views/products/_table.html.erb
<table id="products-list" class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-1">id</th>
      <th class="col-md-2">Image</th>
      <th class="col-md-1">Name</th>
      <th class="col-md-1">Price</th>
      <th class="col-md-2">Categories</th>
      <th class="col-md-3">Description</th>
      <th class="col-md-2">Actions</th>
    </tr>
  </thead>
    <% for @product in @products %>
      <tr>
        <td><%= @product.id %></td>
        <td>
          <% if @product.image? %>
            <img src="<%= @product.image.thumb.url %>" alt="<%= @product.name %>">
          <% else %>
            No image available
          <% end %>
        </td>
        <td><%= @product.name %></td>
        <td><%= @product.price %></td>
        <td>
          <ul>
            <% @product.categories.each do |category| %>
              <li> <%= category.name %> </li>
            <% end %>
          </ul>
        </td>
        <td><%= @product.description %></td>
        <td>
          <a class="btn btn-primary" href="<%= edit_product_path(@product) %>">Edit</a>
        </td>
      </tr>
    <% end %>
</table>
<%= bootstrap_pagination_for(@products) %>

app/views/products/edit.html.erb
Edit product # <%= @product.id %>
<% if logged_in?(:admin) %>
  <%= button_to 'Delete ', @product, :method => :delete, class: 'btn btn-danger pull-right' %>
<% end %>
<%= render partial: 'form', product: @product %>

app/views/products/index.html.erb
<a class="btn btn-primary" href="<%= new_product_path %>">Add New Product</a>

<div id="products">
  <%= render partial: 'table', products: @products %>
</div>

app/views/products/index.js.erb
$("#products").html("<%= escape_javascript(render("table")) %>");

app/views/products/new.html.erb
Create new product

<%= render partial: 'form', product: @product %>

app/views/products/show.html.erb
<h2>Product <%= @product.id %> info</h2>
<div class="row">
  <div class="col-md-3">
    <dl>
      <dt>ID</dt>
      <dd><%= @product.id %></dd>
      <dt>Name</dt>
      <dd><%= @product.name %></dd>
      <dt>Price</dt>
      <dd><%= @product.price%></dd>
      <dt>Description</dt>
      <dd><%= @product.description %></dd>
      <dt>Categories</dt>
      <dd>
        <% unless @product.categories.any? %>
          No categories
        <% end %>

        <ul>
          <%  @product.categories.each do |category| %>
            <li>
              <%= category.name %>
            </li>
          <% end %>
        </ul>
      </dd>
      <dt>Creation time</dt>
      <dd><%= @product.created_at %></dd>
      <dt>Updation time</dt>
      <dd><%= @product.updated_at %></dd>
    </dl>
  </div>
  <div class="col-md-9">
    <img
      src="<%= @product.image.url %>"
      alt="<%= @product.name %>"
    >
  </div>
</div>


<a href="<%= edit_product_path(@product) %>" class="btn btn-primary">Edit</a>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.input :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.input :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.input :password_confirmation, class: 'form-control' %>
  </div>


  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
Edit user # <%= @user.id %>
<%= button_to 'Delete ', @user, :method => :delete, class: 'btn btn-danger pull-right' %>
<%= render partial: 'form', user: @user %>

app/views/users/index.html.erb
<a class="btn btn-primary" href="<%= new_user_path %>">Add New User</a>

<table id="users-list" class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-1">id</th>
      <th>Email</th>
      <th>Roles</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% for @user in @users %>
    <tr>
      <td><%= @user.id %></td>
      <td><%= @user.email %></td>
      <td><%= @user.roles.join(', ') %></td>
      <td>
        <a class="btn btn-primary" href="<%= edit_user_path(@user) %>">Edit</a>
      </td>
    </tr>
  <% end %>
</table>
<%= bootstrap_pagination_for(@products) %>

app/views/users/new.html.erb
Create new user

<%= render partial: 'form', user: @user %>

app/views/users/show.html.erb
<h2>User <%= @user.id %> info</h2>
<dl>
  <dt>ID</dt>
  <dd><%= @user.id %></dd>
  <dt>Email</dt>
  <dd><%= @user.email %></dd>
  <dt>Creation time</dt>
  <dd><%= @user.created_at %></dd>
  <dt>Updation time</dt>
  <dd><%= @user.updated_at %></dd>
</dl>

<a href="<%= edit_user_path(@user) %>" class="btn btn-primary">Edit</a>